openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:

  /eventArchives/{id}:
    get:
      tags:
        - Comment
      summary: Get current event archive
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful displayed all eventArchives
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    rating:
                      type: number
                      format: float
                      nullable: true

                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true


                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
    
    delete:
      tags:
        -  Delete eventArchives
      summary: Delete event archive
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true

      responses:
        '200':
          description: Successful deleted event archive
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean

  /eventArchives:
    post:
      tags:
        -  Create eventArchives
      summary: Create event archive
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:

                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true


      responses:
        '200':
          description: Successful created event archive
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    rating:
                      type: number
                      format: float
                      nullable: true

                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    get:
      tags:
        - EventArchive
      summary: Get all event archive
      responses:
        '200':
          description: Successful displayed all event archive
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        content:
                          type: string
                        rating:
                          type: number
                          format: float
                          nullable: true

                        event_id:
                          type: string
                          format: uuid
                        author_id:
                          type: string
                          format: uuid
                        parent_id:
                          type: string
                          format: uuid
                          nullable: true
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/eventArchives?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/eventArchives?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/eventArchives?page=2
                  path:
                    type: string
                    example: http://localhost/api/eventArchives
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

