openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

# securitySchemes:
# BearerToken:
# type: http
# scheme: bearer
# bearerFormat: JWT
paths:

  /interesters/{id}:
    get:
      tags:
        - Interester
      summary: Get current interester
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful displayed all interesters
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    delete:
      tags:
        -  Delete interesters
      summary: Delete interester
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true

      responses:
        '200':
          description: Successful deleted interester
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean

  /interesters:
    post:
      tags:
        -  Create interesters
      summary: Create interester
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: string
                author_id:
                  type: string


      responses:
        '200':
          description: Successful created interester
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    event_id:
                      type: string
                    author_id:
                      type: string
                      format: uuid

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    get:
      tags:
        - Interesters
      summary: Get all interesters
      responses:
        '200':
          description: Successful displayed all interesters
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        author_id:
                          type: string
                          format: uuid
                        event_id:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/interesters?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/interesters?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/interesters?page=2
                  path:
                    type: string
                    example: http://localhost/api/interesters
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

