openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

# securitySchemes:
# BearerToken:
# type: http
# scheme: bearer
# bearerFormat: JWT
paths:

  /questions/{id}:
    get:
      tags:
        - Question
      summary: Get current question
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful displayed all questions
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true


                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
    put:
      tags:
        - Update question
      summary: update current question
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '200':
          description: Successful updated city
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
    delete:
      tags:
        -  Delete questions
      summary: Delete question
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true

      responses:
        '200':
          description: Successful deleted question
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean

  /questions:
    post:
      tags:
        -  Create questions
      summary: Create question
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:

                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true


      responses:
        '200':
          description: Successful created question
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    content:
                      type: string
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid
                    parent_id:
                      type: string
                      format: uuid
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    get:
      tags:
        - Questions
      summary: Get all questions
      responses:
        '200':
          description: Successful displayed all questions
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        content:
                          type: string
                        event_id:
                          type: string
                          format: uuid
                        author_id:
                          type: string
                          format: uuid
                        parent_id:
                          type: string
                          format: uuid
                          nullable: true
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/questions?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/questions?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/questions?page=2
                  path:
                    type: string
                    example: http://localhost/api/questions
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

