openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

# securitySchemes:
# BearerToken:
# type: http
# scheme: bearer
# bearerFormat: JWT
paths:

  /categories:
    get:
      tags:
        - Categories
      summary: Get all categories
      responses:
        '200':
          description: Successful displayed all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: integer
                      format: int32
                    name:
                      type: string

                example:
                  - id: 1
                    name: frontend
                  - id: 2
                    name: QA
                  - id: 3
                    name: backend

  /categories:
    post:
      tags:
        -  Categories
      summary: Create category
      responses:
        '200':
          description: Successful created category
          content:
            application/json:
              schema:
                type: object
                properties:
                    name:
                      type: string
                    parent_id:
                      type: integer
                      format: int32
                      nullable: true

                example:
                  - id: 1
                    name: cat1
                    parent_id: 2
                  - id: 4
                    name: cat5
                    parent_id:

