openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

# securitySchemes:
# BearerToken:
# type: http
# scheme: bearer
# bearerFormat: JWT
paths:

  /users/{id}:
    get:
      tags:
        - User
      summary: Get current user
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful displayed all users
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                    role:
                      type: string
                    telephone:
                      type: string
                    avatar:
                      type: string
                      nullable: true
                    email_verified_at:
                      type: string
                      nullable: true


                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
    put:
      tags:
        - Update user
      summary: update current user
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  nullable: true
                event_id:
                  type: string
                  format: uuid
                  nullable: true

                password:
                  type: string
                  nullable: true

      responses:
        '200':
          description: Successful updated city
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                    role:
                      type: string
                    telephone:
                      type: string
                    avatar:
                      type: string
                      nullable: true
                    email_verified_at:
                      type: string
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
    delete:
      tags:
        -  Delete users
      summary: Delete user
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true

      responses:
        '200':
          description: Successful deleted user
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean
  /users/{id}/events:
    get:
      tags:
        - User events
      summary: Get all events for current user
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful displayed all users
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                        email:
                          type: string
                          format: email
                        role:
                          type: string
                        telephone:
                          type: string
                        avatar:
                          type: string
                          nullable: true
                        email_verified_at:
                          type: string
                          nullable: true
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/users?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/users?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/users?page=2
                  path:
                    type: string
                    example: http://localhost/api/users
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99
  /users/{id}/avatars/upload:
    post:
      tags:
        -  Upload avatar
      summary: Upload user avatar
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  format: binary

      responses:
        '200':
          description: Successful created question
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                    role:
                      type: string
                    telephone:
                      type: string
                    avatar:
                      type: string
                      nullable: true
                    email_verified_at:
                      type: string
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true
  /users:
    post:
      tags:
        -  Create users
      summary: Create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:

                    name:
                      type: string
                    email:
                      type: string
                      format: email
                    role:
                      type: string
                    telephone:
                      type: string
                    password:
                      type: string


      responses:
        '200':
          description: Successful created user
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    email:
                      type: string
                      format: email
                    role:
                      type: string
                    telephone:
                      type: string
                    avatar:
                      type: string
                      nullable: true
                    email_verified_at:
                      type: string
                      nullable: true

                    created_at:
                      type: string
                      format: date-time
                      nullable: true
                    updated_at:
                      type: string
                      format: date-time
                      nullable: true

    get:
      tags:
        - Users
      summary: Get all users
      responses:
        '200':
          description: Successful displayed all users
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                        email:
                          type: string
                          format: email
                        role:
                          type: string
                        telephone:
                          type: string
                        avatar:
                          type: string
                          nullable: true
                        email_verified_at:
                          type: string
                          nullable: true
                        created_at:
                          type: string
                          format: date-time
                          nullable: true
                        updated_at:
                          type: string
                          format: date-time
                          nullable: true
                  first_page_url:
                    type: string
                    example: http://localhost/api/users?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/users?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/users?page=2
                  path:
                    type: string
                    example: http://localhost/api/users
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

