openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost/api'
    description: local

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /events/{id}/interesters/count:
    get:
      tags:
        - interesters count
      summary: interesters count
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      responses:
        '404':
          $ref: 'exceptions.yaml#/components/responses/eventIsNotFound'
        '200':
          description: Successful created/updated
          content:
            application/json:
              schema:
                type: object
                properties:
                      Appliers:
                        type: integer
  /events/{id}/interesters:
    put:
      tags:
        - Create/delete interester
      summary: create or delete interester
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      security:
        - BearerToken: [ ]
      responses:

        '401':
          $ref: 'exceptions.yaml#/components/responses/userIsNotAuthorize'
        '404':
          description: User or Event not exist
          content:
            application/json:
              schema:
                type: string
              examples:
                UserIsNotExist:
                  value: User is not found
                EventIsNotExist:
                  value: Event is not found
        '403':
          description: Interester is event author
          content:
              application/json:
                schema:
                  example: Interester is event author
        '200':
          description: Successful created/updated
          content:
            application/json:
              schema:
                type: object
                properties:
                      success:
                        type: boolean

  /interesters/{id}:
    get:
      tags:
        - Interester
      summary: Get current interester
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      security:
        - BearerToken: [ ]
      responses:

        '401':
          $ref: 'exceptions.yaml#/components/responses/adminIsNotAuthorize'
        '404':
          description: Interester is not exist
          content:
            application/json:
              schema:
                example: Interester is not found
        '200':
          description: Successful displayed all interesters
          content:
            application/json:
              schema:
                type: object
                properties:
                    id:
                      type: string
                      format: uuid
                    event_id:
                      type: string
                      format: uuid
                    author_id:
                      type: string
                      format: uuid

                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time



  /interesters:
    get:
      tags:
        - Interesters
      summary: Get all interesters
      security:
        - BearerToken: [ ]
      responses:

        '401':
          $ref: 'exceptions.yaml#/components/responses/adminIsNotAuthorize'
        '200':
          description: Successful displayed all interesters
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: string
                    format: int32
                    example: 1
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        author_id:
                          type: string
                          format: uuid
                        event_id:
                          type: string
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                  first_page_url:
                    type: string
                    example: http://localhost/api/interesters?page=1
                  from:
                    type: integer
                    format: int32
                    example: 1
                  last_page:
                    type: integer
                    format: int32
                    example: 10
                  last_page_url:
                    type: string
                    example: http://localhost/api/interesters?page=10
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: nullable
                        label:
                          type: string
                          example: &laquo; Previous
                        active:
                          type: boolean

                  next_page_url:
                    type: string
                    example: http://localhost/api/interesters?page=2
                  path:
                    type: string
                    example: http://localhost/api/interesters
                  per_page:
                    type: integer
                    format: int32
                    example: 10
                  prev_page_url:
                    type: string
                    format: nullable
                  to:
                    type: integer
                    format: int32
                    example: 10
                  total:
                    type: integer
                    format: int32
                    example: 99

